### PR TITLE
Promisify Posting Jobs

### PR DESCRIPTION
**Pull request by sirhodes**
Hey, are you guys (the repo owners) still accepting PRs? I liked the original library, but wanted to make some changes, primarily using Promises instead of the callback approach. If you think it would be worthwhile to merge this in, let me know and I can finish out this PR by updating docs to match new format. If that's not, that's fine too, I can close this if that be the case.

### CODE REVIEW

**Comment by jmalcolm** [comment]
We absolutely accept PRs! We’d love to merge this in.

———————————
Blitline Support


On November 2, 2015 at 9:03:21 PM, Seth Rhodes (notifications@github.com) wrote:

Hey, are you guys (the repo owners) still accepting PRs? I liked the original library, but wanted to make some changes, primarily using Promises instead of the callback approach. If you think it would be worthwhile to merge this in, let me know and I can finish out this PR by updating docs to match new format. If that's not, that's fine too, I can close this if that be the case.

You can view, comment on, or merge this pull request online at:

  https://github.com/blitline-dev/simple_blitline_node/pull/9

Commit Summary

package.json: add bluebird as a dep
blitline: formatting and JSCS comments
blitline: formatting, use Bluebird to promisify postJobs Function
blitline: check jobHash type on addJob
blitline: return the jobs array, useful for debug
2.1.0
File Changes

M lib/blitline.js (109)
M package.json (10)
Patch Links:

https://github.com/blitline-dev/simple_blitline_node/pull/9.patch
https://github.com/blitline-dev/simple_blitline_node/pull/9.diff

**Comment by sirhodes** [comment]
@jmalcolm okay, awesome! I will update the documentation in the README, is there any way you want me to go about rebasing what I've done?

**Comment by sirhodes** [comment]
@jmalcolm is this still wanted?

**Comment by blitline-dev** [comment]
Thanks!

**Comment by gnoff** [comment]
did this remove callback support for postJobs? from a cursory reading of the code, it did, but the version was only bumped as a minor?!?

**Comment by jmalcolm** [comment]
We failed to follow correct semantic versioning. It should have been a 3.x
release, apologies. We will update and fix asap.

-- 
Jason Malcolm
Sent with Airmail

On June 20, 2016 at 3:03:01 PM, Josh Story (notifications@github.com) wrote:

did this remove callback support for postJobs? from a cursory reading of
the code, it did, but the version was only bumped as a minor?!?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/blitline-dev/simple_blitline_node/pull/9#issuecomment-227283696>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAal447QsJ4vk596ll5eRqBuUNkOV7zmks5qNw4SgaJpZM4GaqP0>
.

**Comment by gnoff** [comment]
Thanks @jmalcolm just wanted to make sure I was interpreting it correctly. we got bit by this issue in the past two weeks, not sure why it took us this long to start feeling its effects since it has been in master since Feb. Do you know which version it was introduced in npm specifically? We can accommodate the promise api so we aren't stuck or anything, just surprised.

thanks,
Josh

**Comment by blitline-dev** [comment]
This was entirely our fault. We accepted the change request, but didn’t
re-publish the npm. Then when we DID publish it, (about 2 weeks ago) we
messed up the semantic versioning, and did a minor version, instead of the
proper major version update. I think we have finally fixed the issue.

-- 
Blitline Support
Sent with Airmail

On June 21, 2016 at 6:54:18 AM, Josh Story (notifications@github.com) wrote:

Thanks @jmalcolm <https://github.com/jmalcolm> just wanted to make sure I
was interpreting it correctly. we got bit by this issue in the past two
weeks, not sure why it took us this long to start feeling its effects since
it has been in master since Feb. Do you know which version it was
introduced in npm specifically? We can accommodate the promise api so we
aren't stuck or anything, just surprised.

thanks,
Josh

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/blitline-dev/simple_blitline_node/pull/9#issuecomment-227446741>,
or mute the thread
<https://github.com/notifications/unsubscribe/ABMZL2ht_jiN93OLn_OhjqB3pne6BjWiks5qN-0GgaJpZM4GaqP0>
.

**Pull request merged**
